version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      target: production
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db/wecc_grid
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - DATA_DIR=/app/data
    volumes:
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Frontend service
  frontend:
    build:
      context: ./frontend
    restart: always
    environment:
      - VITE_API_URL=${API_URL}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # PostgreSQL database with PostGIS extension
  db:
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  # Redis for caching
  redis:
    restart: always
    volumes:
      - redis_data:/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/www:/var/www/html
    depends_on:
      - frontend
      - backend
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
